apiVersion: apps/v1
kind: Deployment
metadata:
  name: practo-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: practo-frontend
  template:
    metadata:
      labels:
        app: practo-frontend
    spec:
      containers:
        - name: practo-frontend
          image: practoacr.azurecr.io/practo-frontend:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: practo-frontend
spec:
  type: LoadBalancer
  selector:
    app: practo-frontend
  ports:
    - port: 80
      targetPort: 80
